import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { MainVisual } from 'src/components/MainVisual';
import { Blog } from 'src/components/Blog';
import { Portfolio } from 'src/components/Portfolio';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainVisual />
      <Blog />
      <Portfolio />
    </div>
  );
};

export default Home;
